### ISSUE TITLE
A couple (2?) data visualizations

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#13]
@Mr0grog you've made a ton of progress on this so far...would you like to work with @bengolder to figure out exactly what 1-2 visualizations we should include in the article? Static or dynamic? Real time or summaries of prior data? All that jaz...You seem to have the best sense of what's feasible and the best skills̶z to make it happen.

**Comment by Mr0grog** [comment]
> would you like to work with @bengolder to figure out exactly what 1-2 visualizations we should include in the article?

Yeah, we should do that. That said, visualizations should first and foremost be supportive of the specific arguments being made in the article. There’s room right now to play with different visualizations and data and to experiment, but the specific visualizations should be determined by/supportive of the text @bengolder writes. To put it another way, I think we have a specific story or narrative we want to advance; I don’t think we can determine the relevant illustrations until we have [at least] a good outline or rough draft of that narrative.

> Static or dynamic?

Since I think the narrative _we want to tell_ is primary here, these graphics should tend towards the static. Having some other, more explorable visualizations on the site (?) would be nice, too, but I think that’s secondary. As a related note, though, it would be really awesome to also provide dumps or real-time feeds of the data from pingometer for people to explore on their own (I don’t think we necessarily want to give the public access to administer the pingometer account, but the data it generates should absolutely be publicly/freely/easily available).

> Real time or summaries of prior data?

_For now,_ I think things should generally be real-time, since you are still making updates and changes to the monitoring (e.g. #7 #8 #9 #10). I think we also want to include historical data, though (see trends or patterns).

As far as illustrations for the article, though, we _may_ want to freeze them as of the publication date. Or maybe provide a way for readers to switch between the frozen and current visualizations. (I can’t point to any particular sites, but I feel like I’ve seen some live visualizations occasionally get out of sync with the narrative over time.)

**Comment by bengolder** [comment]
@Mr0grog excited to work with you more. I love your thoughts here.
A [quickly sketched outline for the article is here](https://github.com/codeforamerica/snap-it-up/issues/6#issuecomment-71729103) and some message goals for specific audiences are just above that comment. I'm going to work further on fleshing it out and welcome any suggestions or critiques you might have.
:metal:

**Comment by alanjosephwilliams** [comment]
We address these needs elsewhere—and aspects of it that have not been sufficiently addressed should be articulated in more detail. Closing for now.
