### ISSUE TITLE
Map monitors to states by domain name?

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/snap-it-up#2]
Or by ID. Basically, we need to _not_ do it by `name`, since, even though it was convenient, it’s now broken for California, where all the names recently changed to not be in the format “state | name-of-site”.

**Comment by lippytak** [comment]
Guilty! Sorry about that...yes ID would probably be more stable.

**Comment by Mr0grog** [comment]
Heh, yeah, I knew the name field was probably not going to be very stable when I did it, but it was a convenient hack :)

I’m thinking keying off the hostname would probably be most stable; if monitors are destroyed and recreated or if we switch to another service or who knows what, the hostnames we’re checking _should_ always be the same. That said, some of them have hard-to-grab hostnames, like North Dakota. There’s no hostname, just a series of commands (the first of which is a URL to load).

Actually, now that I’m thinking of it, hostname might not be a good mapping to represent a state. I think it works for SNAP, but it wouldn’t for healthcare, for example (lots of states would all point to healthcare.gov). Grrrr :/

**Comment by bensheldon** [comment]
I suggest just eyeballing a unique slug that has a consistent format like "ca_healthcaregov", "ks_snapinfo" etc. 
- 2-letter state code
- underscore
- single word, all lowercase, that captures something unique about it at the state level, usually the web title rather than the domain itself. Except when using a central multistate service, like healthcare.gov. 

I've done this at about 6 times (4 times for Day of the Shirt and twice with open311status) and going for human-eyeballable clarity of slug (and somewhere to dump notes/metadata alongside where you define that slug) has been the best solution.

**Comment by Mr0grog** [comment]
> I suggest just eyeballing a unique slug that has a consistent format

Well, we had that ;)

I _think_ it was changed because it had to be for statuspage.io to present something sane for users. But @lippytak is the one who actually knows (since he did it).

**Comment by lippytak** [comment]
Correct. I TOLD YOU I'M SORRY!!

**Comment by Mr0grog** [comment]
NEVER LETTING THIS GO, @lippytak. NEVER.

**Comment by Mr0grog** [comment]
Would be nice, actually, if you could tag monitors in @pingometer. Would solve this handily.
