### ISSUE TITLE
Erratic Ohio data

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#25]
Hoping @pingometer can look into this:
![screen shot 2015-02-09 at 8 11 14 am](https://cloud.githubusercontent.com/assets/2533112/6109916/3c9bab08-b033-11e4-9400-c3c3730cd5aa.png)

I've tried to confirm manually and as far as I can tell these are all false positives.

**Comment by Mr0grog** [comment]
FWIW, there have been a bunch of similar up/downs on various California services recently, but they were actual outages, however brief. I checked very quickly on a few; the sites were down for just a minute or two at a time. If I’d checked just a minute later, they would’ve looked like false positives. _Could_ be similar for Ohio.

**Comment by pingometer** [comment]
We looked into the recent events for both monitors - they appear valid.

If you login to the dashboard and go to the Events for Ohio | Online Benefit Application, click the globe icon to view the Root Cause Analysis. For the "UP" events, you'll see the server sets response headers. However, for the "DOWN" events, the response headers are missing for all locations that performed a check (ORD, JER, DAL).

We see this behavior when a server crashes for a moment - usually, it happens when workers/threads are busy. After a minute or two, a few workers/threads become available to respond to new web traffic and the site is back online.
