### ISSUE TITLE
Better keywording for MyBenifts Calwin

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/snap-it-up#26]
It’s down in maintenance mode, but shows as up:

![](https://s3-us-west-2.amazonaws.com/snap-snapshots/CA-54bc8944be653d3f86065dc5-2015-02-17T03%3A38%3A20%2B00%3A00)
https://s3-us-west-2.amazonaws.com/snap-snapshots/CA-54bc8944be653d3f86065dc5-2015-02-17T03%3A38%3A20%2B00%3A00

**Comment by lippytak** [comment]
@pingometer we couldn't do this before because when MBCW first loads via your transaction monitor it throws a JS alert (I think that was it?) and that prevents the rest of the page from loading. Any chance you have a fix for this so we could make this monitor more accurately reflect maintenance down time?

**Comment by pingometer** [comment]
@lippytak I think we might be able to come up with something. We're looking into it now...

**Comment by pingometer** [comment]
@lippytak @Mr0grog Great news! We implemented a change which gets around the popup issue (related to an unsupported browser) on these sites. You can now test them to your heart's content. :)

**Comment by Mr0grog** [comment]
@pingometer woohoo, thanks!

**Comment by lippytak** [comment]
Wonderful! Closing.
