### ISSUE TITLE
Figure out how to keyword check Indiana

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#9]
www.ifcem.com

How is the page even rendering?

**Comment by lippytak** [comment]
Done. And serendipitously confirmed the keyword doesn't appear in the maintenance page:
![screen shot 2015-02-02 at 9 30 40 pm](https://cloud.githubusercontent.com/assets/2533112/6014970/d1ae8820-ab22-11e4-91ce-53a44c2ba86b.png)

**Comment by lippytak** [comment]
@Mr0grog FYI in order to make this change I had to create a new transaction monitor with ID = 54d05a90be653d2e76ff9ce7. I deleted the old Indiana monitor (54a7a0bfbe653d4687bf5ef0).

**Comment by Mr0grog** [comment]
@lippytak Cool, it _should_ still work fine, since we are currently matching state by hostname instead of monitor ID. However, it would be awesome if you updated `public/data/pingometer_monitors.json` with the new ID any time this happens, just in case we switch in the future.

(Note: I just fixed an issue with foolishly assuming we’d always have 7 days of data for every monitor, which was crashing the app… d’oh. But at least we still knew it was Indiana we looking at :P)
